language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-frontend"
  env: "Reactfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-880334749182"
  bucket_path: "react-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY